-- .mockserver/delay.lua
-- Generated by mockserver
---@meta

---@class delay
local delay = {}

---Sleep for the specified number of milliseconds
---@param ms integer Milliseconds to sleep
function delay.sleep(ms) end

return delay
